#!/usr/bin/env bash
# Installs nginx on server web-01
# server listens on port 80
# returns a page with string hello world
sudo apt-get -y update
sudo apt-get -y install nginx
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo /etc/init.d/nginx restart
