#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page

sudo apt-get -y install nginx
# 1 Return a page with 'Hello World' text
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

# redirects /redirect_me to another page
redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "53s|.*|$redirect|" /etc/nginx/sites-enabled/default

# creates custom 404 html page contaning a string
echo "Ceci n'est pas une page" > /usr/share/nginx/html/page_error_404.html
sudo sed -i '37i error_page 404 /page_error_404.html;\nlocation = /page_error_404.html {\nroot /usr/share/nginx/html; \ninternal;\n}\n' /etc/nginx/sites-enabled/default
sudo /etc/init.d/nginx restart
